version: "3"
services:
  apache-php72:
    environment:
      WEBSERVER_PORT: ${WEBSERVER_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    build: ./docker/images/apache-php72
    ports:
      - "${WEBSERVER_PORT}:80"
    volumes:
      - ./:/var/www/html/
    links:
      - mysql
    privileged: true
  mysql:
    image: mariadb
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    privileged: true
  redis:
    image: redis:5
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
